name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: dyalog/dyalog:20.0
      options: --user root

    steps:
      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y nodejs zip unzip

      - uses: actions/checkout@v4

      - name: Activate Tatin and Cider
        run: dyalogscript .github/activate.apls

      - name: Build package
        run: dyalogscript Build.apls

      - name: Publish to Tatin
        run: |
          cd Dist
          dyalogscript ../.github/release.apls
        env:
          TATIN_API_KEY: ${{ secrets.TATIN_API_KEY }}

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: Dist/bkaw-Stark-*.zip
